### ISSUE TITLE
BUG : SSL et VirtualHost

### ISSUE THREAD

**Issue by malnuxstarck** [TokaLazy/oophp#24]
Depuis peu , aprés les maj des navigateurs principales  telsque Chrome ou Firefox , il nous force a utiliser le SSL. c'est qui cause un probleme en local lorsque on cree un virtualhost.

Faut il preciser dans la doc comment cree le vhost et configurer le SSL ?
Moi j'ai un petit Soucis avec le ssl , sans virtualhost on a des soucis aussi

**Comment by TokaLazy** [comment]
🤔 
Je n'ai pas rencontré de problème sur mes différentes machines et je n'ai pas utilisé de SSL.

Est-ce que tu pourrais me dire comment tu procèdes ?

Sinon, la [doc](https://github.com/TokaLazy/oophp/blob/development/docs/commencer.md) et (presque) à jour pour la configuration. Je n'ai pas indiqué comment configurer le vhost mais je peux le mettre si tu sembles ça nécessaire.

**Comment by malnuxstarck** [comment]
Au niveau code et config y'a pas de soucis . J'ai cree un vhost oophp.dev . Tout passe correcte.
Mais mes navigateurs Chrome et Firefox , m'empeche de d'acceder via le vhost en m'indiquand que ma connexion n'est pas securisé. Mais en passant par le chemin localhost/oophp/....etc On a l'afficher mais pour les liens qui mene a des dossier par exemple ça passe pas.

@TokaLazy 🥇

**Comment by malnuxstarck** [comment]
hhh :) Bon une solution c'etait au niveau du sous domaine. On m'informe que oophp(.dev ..) ne passe pas mais oophp.test ça passe. Donc la seule question maitenant faut il ajouté comment faire un vhsot ?
et Franchement Merci tu me fait decouvrir des nouvelles choses 👍

**Comment by TokaLazy** [comment]
Ok ^^
Ça dépend des os, mais évite les vhosts qui finissent par `.test` ou `.dev` (voire meme `.local`)
